const Data = [
    {
        name: 'Aman Kumar',
        about: 'Co-founder and Director of Deez nuts',
        pp: '.././public/images/Speakers_Logo.png',
        twitter_url: 'https://twitter.com/bts_bighit?lang=en',
        instagram_url: 'https://www.instagram.com',
        facebool_url: 'https://www.facebook.com',
    },
    {
        name: 'Aman Kumar',
        about: 'Co-founder and Director of Deez nuts',
        pp: '.././public/images/Speakers_Logo.png',
        twitter_url: 'https://twitter.com/bts_bighit?lang=en',
        instagram_url: 'https://www.instagram.com',
        facebool_url: 'https://www.facebook.com',
    },
    {
        name: 'Aman Kumar',
        about: 'Co-founder and Director of Deez nuts',
        pp: '.././public/images/Speakers_Logo.png',
        twitter_url: 'https://twitter.com/bts_bighit?lang=en',
        instagram_url: 'https://www.instagram.com',
        facebool_url: 'https://www.facebook.com',
    },
    {
        name: 'Aman Kumar',
        about: 'Co-founder and Director of Deez nuts',
        pp: '.././public/images/Speakers_Logo.png',
        twitter_url: 'https://twitter.com/bts_bighit?lang=en',
        instagram_url: 'https://www.instagram.com',
        facebool_url: 'https://www.facebook.com',
    },
    {
        name: 'Aman Kumar',
        about: 'Co-founder and Director of Deez nuts',
        pp: '.././public/images/Speakers_Logo.png',
        twitter_url: 'https://twitter.com/bts_bighit?lang=en',
        instagram_url: 'https://www.instagram.com',
        facebool_url: 'https://www.facebook.com',
    },
    {
        name: 'Aman Kumar',
        about: 'Co-founder and Director of Deez nuts',
        pp: '.././public/images/Speakers_Logo.png',
        twitter_url: 'https://twitter.com/bts_bighit?lang=en',
        instagram_url: 'https://www.instagram.com',
        facebool_url: 'https://www.facebook.com',
    },
    {
        name: 'Aman Kumar',
        about: 'Co-founder and Director of Deez nuts',
        pp: '.././public/images/Speakers_Logo.png',
        twitter_url: 'https://twitter.com/bts_bighit?lang=en',
        instagram_url: 'https://www.instagram.com',
        facebool_url: 'https://www.facebook.com',
    },
]

export default Data
